<?
/**
 * @type Boot_View   $this
 * @var ActiveRecord $resource
 */
use Boot\Auth\Routes;

?>
<h2><?= $this->t('Confirmation instructions') ?></h2>

<? if( Boot_Flash::get('alert') ): ?>
	<div class="error"><?= Boot_Flash::get('alert') ?></div>
<? endif ?>

<? $f = new Boot_Form_Lib(Routes::getName(), new Form_Row(), ['method' => 'post', 'action' => $this->users_confirmed_path()]) ?>
<div class="form-group">
	<?= $f->input('email', ['as' => 'email', 'required' => 'required', 'class' => 'form-control']) ?>
</div>
<?= $f->submit($this->t('Resend confirmation instructions'), ['class' => 'btn btn-primary']) ?>
<? $f->end() ?>

<?= $this->render('shared/_links') ?>
