<?
/**
 * @type Boot_View         $this
 * @var ActiveRecord       $resource
 */
use Boot\Auth\Routes;
?>
<h2><?= $this->t('Forgot your password?') ?></h2>

<? if( $resource->errors->count() ): ?>
	<ul>
		<? foreach( $resource->errors->messages() as $error ): ?>
			<li><?= $error ?></li>
		<? endforeach ?>
	</ul>
<? endif ?>

<? $f = new Boot_Form_Lib(Routes::getName(), $resource, ['method' => 'post', 'action' => $this->{Routes::getName() . "_password_reset_path"}()]) ?>
	<div class="form-group">
		<?= $f->input('email', ['as' => 'email', 'required' => 'required', 'class' => 'form-control']) ?>
	</div>
	<?= $f->submit($this->t('Send me reset password instructions'), ['class' => 'btn btn-primary']) ?>
<? $f->end() ?>

<?= $this->render('shared/_links') ?>
