<?
/**
 * @type Boot_View   $this
 * @var ActiveRecord $resource
 * @var string       $email
 * @var string       $token
 */
use Boot\Auth\Routes;

?>
<p><?= sprintf($this->t('Hello %s!'), $email) ?></p>

<p><?= $this->t('Someone has requested a link to change your password. You can do this through the link below') ?>.</p>

<p><a href="<?= Boot::getInstance()->config->auth->mailer->host ?>/<?= Routes::getName() ?>/password/edit?token=<?= $token ?>"><?= $this->t('Change my password') ?></a></p>

<p><?= $this->t('If you didn\'t request this, please ignore this email.') ?></p>
<p><?= $this->t('Your password won\'t change until you access the link above and create a new one.') ?></p>